server:
  port: 8083


name: abc
#对象格式
person:
  name: zhangsan
  age: 23

#对象行内写法
person2: {name: lisi,age: 24}

#数组
address:
  - beijing
  - shanghai

#数组的行内写法
address2: [ningbo,jinan]

#纯量
msg1: 'hello \n world' #不会识别转义字符
msg2: "hello \n world"  #会识别转义字符